---
- name: Install additional base RaspberryPI packages
  apt: name={{ item }} state=present
  with_items:
    - raspi-copies-and-fills
    - rng-tools
  tags: [ 'tweaks', 'packages' ]

- name: Create swap
  shell: dd if=/dev/zero of=/swap bs=1M count={{ swap_size_mb }} && mkswap /swap && chmod og-r /swap
  args:
    creates: /swap
  tags: [ 'tweaks', 'swap' ]

- name: Enable swap
  lineinfile:
    dest: /etc/fstab
    line: /swap none swap sw 0 0
    state: present
    backup: yes
    create: no
    insertafter: EOF
  tags: [ 'tweaks', 'swap' ]

- name: Enable random number generator module
  lineinfile:
    dest: /etc/modules
    line: bcm2708-rng
    state: present
    backup: yes
  tags: [ 'tweaks', 'rng' ]
